services:
  mysql:
    image: mysql:8.0.35
    container_name: pp-mysql-8.0.35
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pp
      TZ: Asia/Seoul
    volumes:
      - ~/Docker/pp-mysql-8.0.35/data:/var/lib/mysql
  redis:
    image: redis:7.0
    container_name: pp-redis-7.0
    ports:
      - 6379:6379
    volumes:
      - ~/Docker/pp-redis-7.0/data:/data