spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000ms
  datasource:
    url: jdbc:mysql://localhost:3306/pp
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
  security:
    oauth2:
      authorizationserver:
        client:
          kakao:
            registration:
              client-id: kauth.kakao.com
              client-name: kakao
              client-authentication-methods:
                - private_key_jwt
                - none
              authorization-grant-types:
                - client_credentials
                - refresh_token
              scopes:
                - user.read
                - user.write
                - post.read
                - post.write
                - file.write
            token-endpoint-authentication-signing-algorithm: RS256
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            token:
              reuse-refresh-tokens: false
              refresh-token-time-to-live: 30d
          apple:
            registration:
              client-id: appleid.apple.com
              client-name: apple
              client-authentication-methods:
                - private_key_jwt
                - none
              authorization-grant-types:
                - client_credentials
                - refresh_token
              scopes:
                - user.read
                - user.write
                - post.read
                - post.write
                - file.write
            token-endpoint-authentication-signing-algorithm: RS256
            jwk-set-uri: https://appleid.apple.com/auth/oauth2/v2/keys
            token:
              reuse-refresh-tokens: false
              refresh-token-time-to-live: 30d

oauth2:
  jwk:
    - id: ${OAUTH2_JWK_ID}
      type: ${OAUTH2_JWK_TYPE}
      public-key: ${OAUTH2_JWK_PUBLIC_KEY}
      private-key: ${OAUTH2_JWK_PRIVATE_KEY}

client:
  apple:
    base-url: ${CLIENT_APPLE_BASE_URL}
    private-key: ${CLIENT_APPLE_PRIVATE_KEY}
    client-id: ${CLIENT_APPLE_CLIENT_ID}
    client-secret-kid: ${CLIENT_APPLE_SECRET_KID}
    client-secret-issuer: ${CLIENT_APPLE_SECRET_ISSUER}
    client-secret-expiration-days: 30
    token-endpoint: /auth/oauth2/v2/token
    revoke-endpoint: /auth/oauth2/v2/revoke
    connection-timeout: 2000
    read-timeout: 4000
    write-timeout: 3000

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        orm:
          jdbc:
            bind: TRACE